### ISSUE TITLE
As a not logged I would like to be able to count my BMR

### ISSUE THREAD

**Issue by McBlankenburg** [GymRat-s-Logbook/GymRats-Logbook-Backend#5]
**User story:** As a not logged I would like to be able to call the backend with data for information about my BMR

BmrNotLoggedRequest {
      sex: GenderEnum
      dateOfBirth: LocalDate
      weight: float,
      height: float,
      physicalActivityLevel: PhysicalActivityLevelEnum
}

BmrNotLoggedResponse {
     status: int
     message: String
     body: String
}

![image](https://github.com/GymRat-s-Logbook/GymRats-Logbook-Backend/assets/58309339/f1a9b54b-162e-4b6b-bb9a-252b04d8ca2f)

-basis receive feedback containing the appropriate http-code https://http.cat/ and BMI coefficient.
-it is up to the programmer to choose the appropriate BMR counting algorithm.

should be implemented:

BmrNotLoggedRequest
BmrNotLoggedResponse
PhysicalActivityLevelEnum
Unit-tests for counting BMR are required in BDD style (BDDMockito + AssertJ or Junit)
-convention //given //when //then
example --> https://github.com/Simple-as-Coding/tutoring-platform/blob/develop/src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java

**Comment by Julia0321** [comment]
To calculate BMR isn't needed Physical Activity Level as same BMI, It's not needed Gender. So I changed this two cases. Activity Level and gender is needed to ,,Total daily caloric needs".

**Comment by Julia0321** [comment]
Also I changed (in calculateBmi method) height from centimeters to meters.
